### ISSUE TITLE
Request: Allow quoted attribute selector values in order to support values containing space

### ISSUE THREAD

**Issue by clifforama** [akarelas/xml-myxml#5]
In the following contrived example, it would be nice to be able to enclose attribute value in quotes:

```perl
my $xml = <<__XML__;
<people>
    <student name="John Doe">
        <phone>555-555-5555</phone>
    </student>
</people>
__XML__

my $obj = xml_to_object($xml);
print $obj->path('student[name="John Doe"]/phone')->value;
```

Edit: I realized that searching for values containing space already works without quotes. But, it would still be nice to be able to use quotes. This might allow, for example, searching for attribute values that contain square brackets, as in `$obj->path('input[name="foo[]"]')`.

**Comment by akarelas** [comment]
This seems a bit hard. I'll leave this issue open, until I make a fix for it.

**Comment by akarelas** [comment]
Done & Uploaded!

**Comment by clifforama** [comment]
Thanks again for the quick response and solution.

**Comment by akarelas** [comment]
@clifforama Do you mind if I ask you something in private, relating to how you use XML::MyXML? Would you like to send me an email to alex.karelas@gmail.com to start the conversation? Thanks.
